### ISSUE TITLE
LFM那个算法实验跑步起来，求更新

### ISSUE THREAD

**Issue by MeiJiaYun** [lpty/recommendation#2]
在anaconda2的环境和anaconda3的环境下都试了，老是报错，不知道问题出在哪 ; (

**Comment by lpty** [comment]
@MeiJiaYun 你可以把报错信息贴出来看一下

**Comment by MeiJiaYun** [comment]
![image](https://user-images.githubusercontent.com/17883093/34977000-e7f3eab8-fad3-11e7-81d4-0772a35600bd.png)

**Comment by lpty** [comment]
@MeiJiaYun 看一下你数据有没有问题吧 这种问题建议用ide的debug模式调试

**Comment by MeiJiaYun** [comment]
@lpty  嗯嗯，我再调试调试，先谢啦：）

**Comment by einsterm** [comment]
把csv文件中的UserID 改为userId 其他的也一样，首字不大写
