### ISSUE TITLE
数据集好像下载不了了

### ISSUE THREAD

**Issue by XiaoHongbo-Hope** [lpty/recommendation#3]
您好：
        感谢您的代码分享，数据好像没办法下载了，可以拜托重新贴下链接吗

**Comment by lpty** [comment]
@Xiaobenbenben https://grouplens.org/datasets/movielens/1m/，可以的，速度慢自备梯子

**Comment by ithjz** [comment]
http://files.grouplens.org/datasets/movielens/ml-1m.zip
